### PR TITLE
Add Synchronous Support

### PR DESCRIPTION
**Pull request by brockwood**
This pull request contains support for making synchronous requests to etcd.  Due to the nature of the synchronous http(s) request, the nock module is not supported so the unit tests were moved into their own directory.  You easily run them with a 'npm run-script test-sync' but it does require a locally running etcd server.  The test does clean up after itself.

### CODE REVIEW

**Comment by stianeikeland** [comment]
Thanks! The build seems to fail on node 0.8 (because of dependencies). I'll play with it for a bit this weekend, test it out and see if I can't get it run on node 0.8 as well.

(Don't even know If anyone use etcd on node 0.8, might be ok to drop support)

**Comment by brockwood** [comment]
I did a quick test locally with node 0.8 and ran into the following issues:

* the version of npm did not allow me to install some of the modules but a quick 'npm install -g npm' fixed that
* once installed, a module used by the synchronous request library does not work with 0.8. I was able to fix it but that would require sending a pull request to the module's creator.

If you decide that 0.8 support is needed, I can definitely pursue updating that module .

**Comment by stianeikeland** [comment]
Aha, I see.
Btw, I notice a deprecation warning here: https://www.npmjs.com/package/request-sync
Seems the project has been replaced by: https://www.npmjs.com/package/sync-request

I'll try to find some stats on node 0.8 (i've no idea how much usage it has).

**Comment by brockwood** [comment]
I ended up forking sync-request and created https://www.npmjs.com/package/requestsync which is used by this change.  sync-request uses a module called then-request which, while similar to request, is missing features that node-etcd uses for SSL.

**Comment by stianeikeland** [comment]
Played with it some, and seems to work fine on node 0.10 and 0.12 :)

I've merged these changes and are working on them here: https://github.com/stianeikeland/node-etcd/tree/synchronous. I want to see if I can do something smart about the test runner. Maybe do cluster.fork() before the test and fake etcd using a http-server implemented in restify or express. That way the tests can run on travis-ci as well. I'm looking into this, don't know if it's possible yet :)

I guess it's probably ok dropping 0.8 support for new features now that node 0.12 is out. We can release this a a new major, and backport future bugfixes if many people require 0.8 support.

I also tried this on iojs, all the async stuff seem to work fine on iojs ( https://travis-ci.org/stianeikeland/node-etcd/jobs/51774075 ), but the synchronous functions fail.
I guess they have changed something for iojs. I guess it's not a dealbreaker, but do you think it's feasable to get it working there as well? Bleeding edge people will probably start to run stuff on iojs soon.
```
// IOJS:
> e.getSync('a');
Error: _http_client.js:154
    self.agent.addRequest(self, options);
               ^
TypeError: undefined is not a function
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Request.start (/Users/se/Projects/coffee/node-etcd/node_modules/requestsync/node_modules/request/request.js:904:30)
    at Request.end (/Users/se/Projects/coffee/node-etcd/node_modules/requestsync/node_modules/request/request.js:1635:10)
    at end (/Users/se/Projects/coffee/node-etcd/node_modules/requestsync/node_modules/request/request.js:676:14)
    at Immediate._onImmediate (/Users/se/Projects/coffee/node-etcd/node_modules/requestsync/node_modules/request/request.js:690:7)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

    at doRequest (/Users/se/Projects/coffee/node-etcd/node_modules/requestsync/index.js:18:11)
    at Client._multiserverHelper (/Users/se/Projects/coffee/node-etcd/lib/client.js:146:13)
    at Client._multiserverHelper (/Users/se/Projects/coffee/node-etcd/lib/client.js:3:59)
    at Client.execute (/Users/se/Projects/coffee/node-etcd/lib/client.js:78:26)
    at Client.execute (/Users/se/Projects/coffee/node-etcd/lib/client.js:3:59)
    at Client.get (/Users/se/Projects/coffee/node-etcd/lib/client.js:91:17)
    at Client.get (/Users/se/Projects/coffee/node-etcd/lib/client.js:3:59)
    at Etcd.get (/Users/se/Projects/coffee/node-etcd/lib/index.js:64:24)
    at Etcd.getSync (/Users/se/Projects/coffee/node-etcd/lib/index.js:72:17)
    at repl:1:3```

**Comment by brockwood** [comment]
I will take a look at iojs this evening and see if I can find out what the problem is there.  I have also submitted a pull request to fix the upstream module that is breaking 0.8.  I've tested that locally and it works fine so hopefully the pull request is taken.

**Comment by stianeikeland** [comment]
Great! Thank you :)

**Comment by brockwood** [comment]
Out of curiosity, how are you testing the sync code on iojs? Is it on OSX?  When I run test-sync on Linux, it shows passing:

```bash
[brock97@rock-dev node-etcd]$ pwd
/home/brock97/src/stianeikeland/node-etcd
[brock97@rock-dev node-etcd]$ git status
# On branch synchronous
nothing to commit, working directory clean
[brock97@rock-dev node-etcd]$ node -v
v1.3.0
[brock97@rock-dev node-etcd]$ npm -v
2.5.1
[brock97@rock-dev node-etcd]$ npm run-script test-sync

> node-etcd@3.0.2 test-sync /home/brock97/src/stianeikeland/node-etcd
> node_modules/mocha/bin/mocha --compilers coffee:coffee-script test/sync/sync.coffee

child_process: customFds option is deprecated, use stdio instead.

  ․․․․․․

  6 passing (993ms)

[brock97@rock-dev node-etcd]$
```

**Comment by stianeikeland** [comment]
Oh! Interesting! Yeah, it's on OS X, that might mean there is something strange with my setup. I'll try again in vagrant on a clean Linux.

**Comment by brockwood** [comment]
A quick followup.  I am unable to reproduce it on OSX either.  Hopefully it is just your setup.  :sweat_smile: 

```bash
BRocksWkBookPro:node-etcd brock97$ pwd
/Users/brock97/src/stianeikeland/node-etcd
BRocksWkBookPro:node-etcd brock97$ git status
On branch synchronous
Your branch is up-to-date with 'origin/synchronous'.

nothing to commit, working directory clean
BRocksWkBookPro:node-etcd brock97$ node -v
v1.3.0
BRocksWkBookPro:node-etcd brock97$ npm -v
2.5.1
BRocksWkBookPro:node-etcd brock97$ npm run-script test-sync

> node-etcd@3.0.2 test-sync /Users/brock97/src/stianeikeland/node-etcd
> node_modules/mocha/bin/mocha --compilers coffee:coffee-script test/sync/sync.coffee

child_process: customFds option is deprecated, use stdio instead.

  ․․․․․․

  6 passing (2s)

BRocksWkBookPro:node-etcd brock97$
```

**Comment by stianeikeland** [comment]
Retried with with iojs running via nvm. Works! So yeah, must have been my setup.
I guess something was broken with my manually installed iojs.

**Comment by brockwood** [comment]
That's great to hear.  I have pushed a change to requestsync that fixes the issue with Node 0.8.  The only caveat is that I had to upgrade npm to npm@1.4.0 for the install to work in v0.8.  This is due to the fact that the version of npm that Travis is using for this test is so old (see [the comment on this issue](https://github.com/rlidwka/sinopia/issues/49#issuecomment-36779628)), it does not support the caret (^) operator in the package.json.  If you do not mind upgrading the NPM version for the test, it should now finish successfully.

**Comment by stianeikeland** [comment]
I've added a small mocked etcd-like rest server to avoid having to run etcd during tests.
https://github.com/stianeikeland/node-etcd/tree/synchronous

If you run the following all tests should pass:
```node_modules/.bin/mocha --compilers coffee:coffee-script/register test/sync/ test/```

However, I noticed something weird.. if I run the sync tests last, it fails:
```node_modules/.bin/mocha --compilers coffee:coffee-script/register test/ test/sync/

     Error: _http_client.js:154
    self.agent.addRequest(self, options);
               ^
TypeError: undefined is not a function
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Request.start (/Users/se/Projects/coffee/node-etcd/node_modules/request/request.js:904:30)
    at Request.end (/Users/se/Projects/coffee/node-etcd/node_modules/request/request.js:1635:10)
    at end (/Users/se/Projects/coffee/node-etcd/node_modules/request/request.js:676:14)
    at Immediate._onImmediate (/Users/se/Projects/coffee/node-etcd/node_modules/request/request.js:690:7)
    at processImmediate [as _immediateCallback] (timers.js:358:17)```

Any idea why? Is it conflicting with nock maybe?

**Comment by brockwood** [comment]
Wow.  Excellent addition with the mock etcd server... wish I had thought of that.  Let me pull down the latest and see if I can find out what is going on.

**Comment by brockwood** [comment]
So I discovered the issue and it is with the upstream requestsync module.  I have a fix but, while researching this problem, I found another solution that I feel is much cleaner.  Unfortunately, it would break compatibility with node 0.8.  By using the 'deasync' module, I would be able to code the synchronous support so that the synchronous tests would be able to utilize nock in the main test file.  So, there are two options here:

1.  I can push a fix for requestsync that will solve the issue you are seeing.
1.  I can instead update the pull request to use the 'deasync' module which would break support for node 0.8 but would allow node-etcd to use the request module for both sync and async requests and allow all tests to run against nock.

I would personally prefer option 2 since it would be cleaner and, potentially, more stable because requestsync is a very new module.  The question then becomes how important is node 0.8 support.  If you would prefer to go with option 1, I would then make sure that test coverage in requestsync greatly improves.

**Comment by stianeikeland** [comment]
Great! Yeah, I agree, let's go for option 2. We'll release this as a new major with support for iojs, node 0.12 and 0.10 - it will allow me to bump other dependencies as well. I'll backport future fixes to the current major version if there's demand for 0.8

**Comment by brockwood** [comment]
Pull request updated.  I see that the Travis build is still failing but it is in iojs and in the cluster support.  Otherwise the test looks good.

**Comment by stianeikeland** [comment]
I reran the travis build - and it worked.. So I'm guessing it was an unrelated fluke of some sort, travis issue, iojs issue, or problem in the other tests, or similar.

Thanks, will give this a try tonight.
